
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mekanismmoremachine"
version="1.0"
displayName="Mekanism: More Machine"
authors="FixedDolphin927"

description='''${mod_description}'''
[[dependencies.mekanismmoremachine]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.mekanismmoremachine]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
